import '@/styles/global.scss'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import GenerateSquareSpin from '@/components/animation/GenerateSquareSpin'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Walid Profile',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <section>
          <GenerateSquareSpin length={150} typeOfElement='span' shape='square' vw='80' vh='80' maxBrightness='100' />
        </section>
      </body>
    </html>
  )
}
